# Copyright AI-Catalog Contributors (https://github.com/Agent-Card/ai-catalog-cli)
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: release-crates

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-crates:
    name: Release catalog crates
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run release-plz
        uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: release
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml

  release-crates-pr:
    name: Release catalog crates - PR
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run release-plz - PR
        uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: release-pr
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml
